# Generated by Django 5.1.15 on 2026-09-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('headline', models.CharField(blank=True, default='Active Job Seeker', max_length=255)),
                ('target_role', models.CharField(blank=True, default='Software Engineer', max_length=150)),
                ('experience_years', models.FloatField(default=1.0)),
                ('education_level', models.CharField(choices=[('Bachelors', "Bachelor's Degree"), ('Masters', "Master's Degree"), ('Doctorate', 'PhD / Doctorate'), ('Associate', 'Associate Degree'), ('SelfTaught', 'Self Taught / BootCamp')], default='Bachelors', max_length=50)),
                ('location', models.CharField(blank=True, default='Remote / Hybrid', max_length=150)),
                ('target_salary', models.IntegerField(default=85000, help_text='Target annual salary in USD')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
