# Generated by Django 5.1.15 on 2026-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('BTech', 'B.Tech / B.E. (Computer Science / IT / Circuit)'), ('MTech', 'M.Tech / M.E.'), ('BCA_BSc', 'BCA / B.Sc (Computer Science / IT)'), ('MCA_MSc', 'MCA / M.Sc (Computer Science / IT)'), ('Doctorate', 'PhD / Doctorate'), ('SelfTaught', 'Self Taught / BootCamp')], default='BTech', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, default='Software Development Engineer (SDE)', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Bengaluru / Remote', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_role',
            field=models.CharField(blank=True, default='Full Stack Developer / SDE', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_salary',
            field=models.IntegerField(default=1200000, help_text='Target annual salary in INR (₹) e.g. 1200000 for 12 LPA'),
        ),
    ]
