# Generated by Django 5.1.15 on 2026-09-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(default='Remote', max_length=200)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=50)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], default='Remote', max_length=50)),
                ('salary', models.CharField(blank=True, help_text='e.g. $100k - $130k or $60/hr', max_length=100, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('required_skills_text', models.TextField(blank=True, help_text='Comma-separated skills string')),
                ('preferred_skills_text', models.TextField(blank=True)),
                ('experience_required', models.FloatField(default=1.0, help_text='Years of experience required')),
                ('education', models.CharField(default="Bachelor's", max_length=100)),
                ('source', models.CharField(default='LinkedIn', max_length=100)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_saved'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_instances', to='skills.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
