# Generated by Django 5.1.15 on 2026-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(default='B.Tech / B.E.', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Bengaluru', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='e.g. ₹8 LPA - ₹15 LPA or ₹30,000/mo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(default='Naukri.com', max_length=100),
        ),
    ]
