# Generated by Django 5.1.15 on 2026-09-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Software Engineering Resume', max_length=200)),
                ('summary', models.TextField(blank=True, default='Passionate software engineer with strong full-stack skills.')),
                ('education_data', models.TextField(blank=True, default='B.S. in Computer Science')),
                ('experience_data', models.TextField(blank=True, default='Software Engineer Intern | Developed REST APIs & React UI')),
                ('projects_data', models.TextField(blank=True, default='JobFlow SaaS Platform, E-Commerce App')),
                ('skills_summary', models.TextField(blank=True, default='React, JavaScript, Python, Django, MySQL, Git, Tailwind CSS')),
                ('certifications', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
