# Generated by Django 5.1.15 on 2026-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
